AWSTemplateFormatVersion: "2010-09-09"

Resources:
# ------------------------------------------------------------#
#  WAF v1
# ------------------------------------------------------------#
  BlockStringSetUAIE6:
    Type: "AWS::WAF::ByteMatchSet"
# グローバルでなくリージョンで使用したい場合は以下
#    Type: "AWS::WAFRegional::ByteMatchSet
    Properties:
      Name: "restrict-user-agent-IE6"
      ByteMatchTuples:
        -
# UA で IE6 をブロックする場合
          FieldToMatch:
            Type: "HEADER"
            Data: "User-Agent"
          TargetString: "Mozilla/4.0 (compatible; MSIE 6.0;"
          TextTransformation: "NONE"
          PositionalConstraint: "CONTAINS"
  BlockStringRules:
    Type: "AWS::WAF::Rule"
    Properties:
      Name: "ua-block-rules"
      MetricName: "BlockStringRules"
      Predicates:
        -
          DataId:
            Ref: "BlockStringSetUAIE6"
          Negated: false
          Type: "ByteMatch"
