AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyIPSetBlacklist: 
    Type: "AWS::WAFRegional::IPSet"
    Properties: 
      Name: "ip-block-list"
      IPSetDescriptors: 
        - 
          Type: "IPV4"
          Value: "XXX.XXX.XXX.XXX/32"  # 拒否したい IP を記載
        - 
          Type: "IPV4"
          Value: "XXX.XXX.XXX.XXX/32"  # 拒否したい IP を記載
  MyIPSetRule: 
    Type: "AWS::WAFRegional::Rule"
    Properties: 
      Name: "ip-block-rules"
      MetricName: "MyIPSetRule"
      Predicates: 
        - 
          DataId: 
            Ref: "MyIPSetBlacklist"
          Negated: false
          Type: "IPMatch"