AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SqlInjDetection: 
    Type: "AWS::WAFRegional::SqlInjectionMatchSet"
    Properties: 
      Name: "generic-detect-sqli"
      SqlInjectionMatchTuples: 
          - FieldToMatch:
              Type: URI
            TextTransformation: URL_DECODE
          - FieldToMatch:
              Type: URI
            TextTransformation: HTML_ENTITY_DECODE
          - FieldToMatch:
              Type: QUERY_STRING
            TextTransformation: URL_DECODE
          - FieldToMatch:
              Type: QUERY_STRING
            TextTransformation: HTML_ENTITY_DECODE
          - FieldToMatch:
              Type: HEADER
              Data: cookie
            TextTransformation: URL_DECODE
          - FieldToMatch:
              Type: HEADER
              Data: cookie
            TextTransformation: HTML_ENTITY_DECODE
  SqlInjRule: 
    Type: "AWS::WAFRegional::Rule"
    Properties: 
      Name: "generic-detect-sqli-rules"
      MetricName: "SqlInjRule"
      Predicates: 
        - 
          DataId: 
            Ref: "SqlInjDetection"
          Negated: false
          Type: "SqlInjectionMatch"
